name: Build

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:22
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set release to true
        run: |
          sed 's/return\ false\;\ \/\/\ set\ automatically/return\ true/g' src/lib/index.ts
      - name: Build the extension
        run: |
          npm install
          npm run build
      - name: Upload extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            dist
