name: Build

on:
  release

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:22
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Set release flag"
        run: |
          sed -i 's/\"isRelease\"\: false\,/\"isRelease\"\: true\,/g' src/data.json
      - name: Build the extension
        run: |
          npm install
          npm run build
      - name: Upload extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            dist
