name: Build

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:22
    steps:
      - name: build extension
      - uses: actions/checkout@v3
        with:
          node-version: 22
      - run: npm install
      - run: npm run build
      - name: create artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            dist
